In [46]:
import torch
import torchvision


img = torchvision.io.image.read_image('datasets/angle/raw_frames/video_0/frame_0.jpg')
img

tensor([[[154, 154, 154,  ..., 213, 213, 213],
         [154, 154, 154,  ..., 213, 213, 213],
         [154, 154, 154,  ..., 213, 213, 213],
         ...,
         [110, 109, 108,  ...,  61,  61,  61],
         [112, 111, 110,  ...,  61,  61,  61],
         [113, 112, 111,  ...,  62,  62,  62]],

        [[136, 136, 136,  ..., 189, 189, 189],
         [136, 136, 136,  ..., 189, 189, 189],
         [136, 136, 136,  ..., 189, 189, 189],
         ...,
         [ 52,  51,  50,  ...,  67,  67,  67],
         [ 54,  53,  52,  ...,  67,  67,  67],
         [ 55,  54,  53,  ...,  68,  68,  68]],

        [[114, 114, 114,  ..., 163, 163, 163],
         [114, 114, 114,  ..., 163, 163, 163],
         [114, 114, 114,  ..., 163, 163, 163],
         ...,
         [ 12,  11,  10,  ...,  57,  57,  57],
         [ 14,  13,  12,  ...,  57,  57,  57],
         [ 15,  14,  13,  ...,  58,  58,  58]]], dtype=torch.uint8)

In [95]:
torchvision.io.image.write_png(img, 'saved_img.jpg', compression_level=9)

In [96]:
saved_img = torchvision.io.image.read_image('saved_img.jpg')

In [97]:
saved_img

tensor([[[154, 154, 154,  ..., 213, 213, 213],
         [154, 154, 154,  ..., 213, 213, 213],
         [154, 154, 154,  ..., 213, 213, 213],
         ...,
         [110, 109, 108,  ...,  61,  61,  61],
         [112, 111, 110,  ...,  61,  61,  61],
         [113, 112, 111,  ...,  62,  62,  62]],

        [[136, 136, 136,  ..., 189, 189, 189],
         [136, 136, 136,  ..., 189, 189, 189],
         [136, 136, 136,  ..., 189, 189, 189],
         ...,
         [ 52,  51,  50,  ...,  67,  67,  67],
         [ 54,  53,  52,  ...,  67,  67,  67],
         [ 55,  54,  53,  ...,  68,  68,  68]],

        [[114, 114, 114,  ..., 163, 163, 163],
         [114, 114, 114,  ..., 163, 163, 163],
         [114, 114, 114,  ..., 163, 163, 163],
         ...,
         [ 12,  11,  10,  ...,  57,  57,  57],
         [ 14,  13,  12,  ...,  57,  57,  57],
         [ 15,  14,  13,  ...,  58,  58,  58]]], dtype=torch.uint8)

In [98]:
mask = saved_img == img
torch.where(mask == False)[0].shape

torch.Size([0])

In [102]:
import torch
import torchvision.models as models

# Load a pre-trained ResNet model (e.g., ResNet-18)
model = models.resnet101()

x = torch.rand(8, 3, 224, 224)
model(x)

tensor([[ 0.2593, -0.6745, -0.0197,  ...,  0.3730,  1.1357, -0.0158],
        [ 0.2435, -0.4927,  0.0948,  ...,  0.4186,  1.4228, -0.0972],
        [ 0.2796, -0.5648, -0.0433,  ...,  0.3549,  1.0805, -0.0643],
        ...,
        [ 0.2464, -0.6769, -0.1230,  ...,  0.6125,  1.3464,  0.0676],
        [ 0.2844, -0.6233, -0.0479,  ...,  0.4338,  1.1652,  0.0280],
        [ 0.0852, -0.5187, -0.0731,  ...,  0.4913,  1.2703,  0.1097]],
       grad_fn=<AddmmBackward0>)